{% set version = "2.2.0" %}

package:
  name: convertdate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/convertdate/convertdate-{{ version }}.tar.gz
  sha256: 9d2b0cd8d5382d2458d4cfa59665abba398a9e9bfd3a01c6f61b7b47768d28bf

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - ephem >=3.7.5.3,<3.8
    - pytz >=2014.10,<2020

test:
  imports:
    - convertdate
    - convertdate.data

about:
  home: https://github.com/fitnr/convertdate
  license: MIT
  license_file: LICENSE
  summary: 'Converts between Gregorian dates and other calendar systems'

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
