{% set version = "2.4.0" %}

package:
  name: convertdate
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/convertdate/convertdate-{{ version }}.tar.gz
  sha256: 770c6b2195544d3e451e230b3f1c9b121ed02680b877f896306a04cf6f26b48f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pymeeus <=1,>=0.3.6
    - pytz >=2014.10


test:
  imports:
    - convertdate
    - convertdate.data
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fitnr/convertdate
  license: MIT
  license_file: LICENSE
  summary: "Converts between Gregorian dates and other calendar systems.Calendars included: Baha'i, French Republican, Hebrew, Indian Civil, Islamic, ISO, Julian, Mayan and Persian."

extra:
  recipe-maintainers:
    - tacaswell
    - ocefpaf
